sql:
  username: root
  password: 123456
  db-name: localhost:3306
jwt:
  # if using rsa, support file path to private key and public key
  using-rsa: true
  #rsa authentication
  private-key-path: "rsa/app.rsa"
  public-key-path: "rsa/app.rsa.pub"
  #hsa authentication
  signing-key: "demo"
